// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Dailiduzhou/library_manage_sys/controllers"
	"github.com/Dailiduzhou/library_manage_sys/repositories"
	"github.com/Dailiduzhou/library_manage_sys/services"
	"github.com/google/wire"
	"gorm.io/gorm"
)

import (
	_ "github.com/Dailiduzhou/library_manage_sys/docs"
)

// Injectors from wire.go:

func initializeHandlers(db *gorm.DB) (*appHandlers, error) {
	bookRepository := repositories.NewGormBookRepository(db)
	bookService := services.NewBookService(bookRepository)
	bookHandler := controller.NewBookHandler(bookService)
	userRepository := repositories.NewGormUserRepository(db)
	userService := services.NewUserService(userRepository)
	userHandler := controller.NewUserHandler(userService)
	borrowRepository := repositories.NewGormBorrowRepository(db)
	transactor := repositories.NewGormTransactor(db)
	borrowService := services.NewBorrowService(borrowRepository, bookRepository, transactor)
	borrowHandler := controller.NewBorrowHandler(borrowService)
	mainAppHandlers := &appHandlers{
		book:   bookHandler,
		user:   userHandler,
		borrow: borrowHandler,
	}
	return mainAppHandlers, nil
}

// wire.go:

var repositorySet = wire.NewSet(repositories.NewGormBookRepository, repositories.NewGormUserRepository, repositories.NewGormBorrowRepository, repositories.NewGormTransactor)

var serviceSet = wire.NewSet(services.NewBookService, services.NewUserService, services.NewBorrowService)

var handlerSet = wire.NewSet(controller.NewBookHandler, controller.NewUserHandler, controller.NewBorrowHandler)
