// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks/mock_interfaces.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/Dailiduzhou/library_manage_sys/models"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockBookRepository is a mock of BookRepository interface.
type MockBookRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBookRepositoryMockRecorder
	isgomock struct{}
}

// MockBookRepositoryMockRecorder is the mock recorder for MockBookRepository.
type MockBookRepositoryMockRecorder struct {
	mock *MockBookRepository
}

// NewMockBookRepository creates a new mock instance.
func NewMockBookRepository(ctrl *gomock.Controller) *MockBookRepository {
	mock := &MockBookRepository{ctrl: ctrl}
	mock.recorder = &MockBookRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookRepository) EXPECT() *MockBookRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBookRepository) Create(db *gorm.DB, book *models.Book) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", db, book)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBookRepositoryMockRecorder) Create(db, book any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBookRepository)(nil).Create), db, book)
}

// Delete mocks base method.
func (m *MockBookRepository) Delete(db *gorm.DB, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", db, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBookRepositoryMockRecorder) Delete(db, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBookRepository)(nil).Delete), db, id)
}

// FindAll mocks base method.
func (m *MockBookRepository) FindAll(db *gorm.DB) ([]*models.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", db)
	ret0, _ := ret[0].([]*models.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockBookRepositoryMockRecorder) FindAll(db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockBookRepository)(nil).FindAll), db)
}

// FindByAuthor mocks base method.
func (m *MockBookRepository) FindByAuthor(db *gorm.DB, author string) ([]*models.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByAuthor", db, author)
	ret0, _ := ret[0].([]*models.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByAuthor indicates an expected call of FindByAuthor.
func (mr *MockBookRepositoryMockRecorder) FindByAuthor(db, author any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByAuthor", reflect.TypeOf((*MockBookRepository)(nil).FindByAuthor), db, author)
}

// FindByTitle mocks base method.
func (m *MockBookRepository) FindByTitle(db *gorm.DB, title string) ([]*models.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTitle", db, title)
	ret0, _ := ret[0].([]*models.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTitle indicates an expected call of FindByTitle.
func (mr *MockBookRepositoryMockRecorder) FindByTitle(db, title any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTitle", reflect.TypeOf((*MockBookRepository)(nil).FindByTitle), db, title)
}

// GetByID mocks base method.
func (m *MockBookRepository) GetByID(db *gorm.DB, id uint) (*models.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", db, id)
	ret0, _ := ret[0].(*models.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockBookRepositoryMockRecorder) GetByID(db, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockBookRepository)(nil).GetByID), db, id)
}

// Update mocks base method.
func (m *MockBookRepository) Update(db *gorm.DB, book *models.Book) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", db, book)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockBookRepositoryMockRecorder) Update(db, book any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBookRepository)(nil).Update), db, book)
}

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRepository) Create(db *gorm.DB, user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", db, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryMockRecorder) Create(db, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepository)(nil).Create), db, user)
}

// FindAll mocks base method.
func (m *MockUserRepository) FindAll(db *gorm.DB) ([]*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", db)
	ret0, _ := ret[0].([]*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockUserRepositoryMockRecorder) FindAll(db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockUserRepository)(nil).FindAll), db)
}

// GetByID mocks base method.
func (m *MockUserRepository) GetByID(db *gorm.DB, id uint) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", db, id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepositoryMockRecorder) GetByID(db, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepository)(nil).GetByID), db, id)
}

// GetByUsername mocks base method.
func (m *MockUserRepository) GetByUsername(db *gorm.DB, username string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUsername", db, username)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUsername indicates an expected call of GetByUsername.
func (mr *MockUserRepositoryMockRecorder) GetByUsername(db, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUsername", reflect.TypeOf((*MockUserRepository)(nil).GetByUsername), db, username)
}

// MockBorrowRepository is a mock of BorrowRepository interface.
type MockBorrowRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBorrowRepositoryMockRecorder
	isgomock struct{}
}

// MockBorrowRepositoryMockRecorder is the mock recorder for MockBorrowRepository.
type MockBorrowRepositoryMockRecorder struct {
	mock *MockBorrowRepository
}

// NewMockBorrowRepository creates a new mock instance.
func NewMockBorrowRepository(ctrl *gomock.Controller) *MockBorrowRepository {
	mock := &MockBorrowRepository{ctrl: ctrl}
	mock.recorder = &MockBorrowRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBorrowRepository) EXPECT() *MockBorrowRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBorrowRepository) Create(db *gorm.DB, record *models.BorrowRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", db, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBorrowRepositoryMockRecorder) Create(db, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBorrowRepository)(nil).Create), db, record)
}

// FindAll mocks base method.
func (m *MockBorrowRepository) FindAll(db *gorm.DB) ([]*models.BorrowRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", db)
	ret0, _ := ret[0].([]*models.BorrowRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockBorrowRepositoryMockRecorder) FindAll(db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockBorrowRepository)(nil).FindAll), db)
}

// GetByBookID mocks base method.
func (m *MockBorrowRepository) GetByBookID(db *gorm.DB, bookID uint) ([]*models.BorrowRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByBookID", db, bookID)
	ret0, _ := ret[0].([]*models.BorrowRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByBookID indicates an expected call of GetByBookID.
func (mr *MockBorrowRepositoryMockRecorder) GetByBookID(db, bookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByBookID", reflect.TypeOf((*MockBorrowRepository)(nil).GetByBookID), db, bookID)
}

// GetByID mocks base method.
func (m *MockBorrowRepository) GetByID(db *gorm.DB, id uint) (*models.BorrowRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", db, id)
	ret0, _ := ret[0].(*models.BorrowRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockBorrowRepositoryMockRecorder) GetByID(db, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockBorrowRepository)(nil).GetByID), db, id)
}

// GetByUserAndBook mocks base method.
func (m *MockBorrowRepository) GetByUserAndBook(db *gorm.DB, userID, bookID uint) (*models.BorrowRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserAndBook", db, userID, bookID)
	ret0, _ := ret[0].(*models.BorrowRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserAndBook indicates an expected call of GetByUserAndBook.
func (mr *MockBorrowRepositoryMockRecorder) GetByUserAndBook(db, userID, bookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserAndBook", reflect.TypeOf((*MockBorrowRepository)(nil).GetByUserAndBook), db, userID, bookID)
}

// GetByUserID mocks base method.
func (m *MockBorrowRepository) GetByUserID(db *gorm.DB, userID uint) ([]*models.BorrowRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", db, userID)
	ret0, _ := ret[0].([]*models.BorrowRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockBorrowRepositoryMockRecorder) GetByUserID(db, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockBorrowRepository)(nil).GetByUserID), db, userID)
}
