// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks/mock_interfaces.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/Dailiduzhou/library_manage_sys/models"
	gomock "go.uber.org/mock/gomock"
)

// MockBookRepository is a mock of BookRepository interface.
type MockBookRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBookRepositoryMockRecorder
	isgomock struct{}
}

// MockBookRepositoryMockRecorder is the mock recorder for MockBookRepository.
type MockBookRepositoryMockRecorder struct {
	mock *MockBookRepository
}

// NewMockBookRepository creates a new mock instance.
func NewMockBookRepository(ctrl *gomock.Controller) *MockBookRepository {
	mock := &MockBookRepository{ctrl: ctrl}
	mock.recorder = &MockBookRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookRepository) EXPECT() *MockBookRepositoryMockRecorder {
	return m.recorder
}

// CreateBook mocks base method.
func (m *MockBookRepository) CreateBook(book *models.Book) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBook", book)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBook indicates an expected call of CreateBook.
func (mr *MockBookRepositoryMockRecorder) CreateBook(book any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBook", reflect.TypeOf((*MockBookRepository)(nil).CreateBook), book)
}

// DeleteBook mocks base method.
func (m *MockBookRepository) DeleteBook(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBook", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBook indicates an expected call of DeleteBook.
func (mr *MockBookRepositoryMockRecorder) DeleteBook(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBook", reflect.TypeOf((*MockBookRepository)(nil).DeleteBook), id)
}

// FindBooksByAuthor mocks base method.
func (m *MockBookRepository) FindBooksByAuthor(author string) ([]*models.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBooksByAuthor", author)
	ret0, _ := ret[0].([]*models.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBooksByAuthor indicates an expected call of FindBooksByAuthor.
func (mr *MockBookRepositoryMockRecorder) FindBooksByAuthor(author any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBooksByAuthor", reflect.TypeOf((*MockBookRepository)(nil).FindBooksByAuthor), author)
}

// FindBooksByTitle mocks base method.
func (m *MockBookRepository) FindBooksByTitle(title string) ([]*models.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBooksByTitle", title)
	ret0, _ := ret[0].([]*models.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBooksByTitle indicates an expected call of FindBooksByTitle.
func (mr *MockBookRepositoryMockRecorder) FindBooksByTitle(title any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBooksByTitle", reflect.TypeOf((*MockBookRepository)(nil).FindBooksByTitle), title)
}

// GetBookByID mocks base method.
func (m *MockBookRepository) GetBookByID(id uint) (*models.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookByID", id)
	ret0, _ := ret[0].(*models.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookByID indicates an expected call of GetBookByID.
func (mr *MockBookRepositoryMockRecorder) GetBookByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookByID", reflect.TypeOf((*MockBookRepository)(nil).GetBookByID), id)
}

// ListBooks mocks base method.
func (m *MockBookRepository) ListBooks() ([]*models.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBooks")
	ret0, _ := ret[0].([]*models.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBooks indicates an expected call of ListBooks.
func (mr *MockBookRepositoryMockRecorder) ListBooks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBooks", reflect.TypeOf((*MockBookRepository)(nil).ListBooks))
}

// LockBookForUpdate mocks base method.
func (m *MockBookRepository) LockBookForUpdate(id uint) (*models.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockBookForUpdate", id)
	ret0, _ := ret[0].(*models.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LockBookForUpdate indicates an expected call of LockBookForUpdate.
func (mr *MockBookRepositoryMockRecorder) LockBookForUpdate(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockBookForUpdate", reflect.TypeOf((*MockBookRepository)(nil).LockBookForUpdate), id)
}

// SaveLockedBook mocks base method.
func (m *MockBookRepository) SaveLockedBook(book *models.Book) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveLockedBook", book)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveLockedBook indicates an expected call of SaveLockedBook.
func (mr *MockBookRepositoryMockRecorder) SaveLockedBook(book any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveLockedBook", reflect.TypeOf((*MockBookRepository)(nil).SaveLockedBook), book)
}

// UpdateBook mocks base method.
func (m *MockBookRepository) UpdateBook(book *models.Book) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBook", book)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBook indicates an expected call of UpdateBook.
func (mr *MockBookRepositoryMockRecorder) UpdateBook(book any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBook", reflect.TypeOf((*MockBookRepository)(nil).UpdateBook), book)
}

// UpdateBookStockWithTotal mocks base method.
func (m *MockBookRepository) UpdateBookStockWithTotal(id uint, newStock, newTotalStock int) (*models.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBookStockWithTotal", id, newStock, newTotalStock)
	ret0, _ := ret[0].(*models.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBookStockWithTotal indicates an expected call of UpdateBookStockWithTotal.
func (mr *MockBookRepositoryMockRecorder) UpdateBookStockWithTotal(id, newStock, newTotalStock any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBookStockWithTotal", reflect.TypeOf((*MockBookRepository)(nil).UpdateBookStockWithTotal), id, newStock, newTotalStock)
}

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRepository) Create(user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryMockRecorder) Create(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepository)(nil).Create), user)
}

// FindAll mocks base method.
func (m *MockUserRepository) FindAll() ([]*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].([]*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockUserRepositoryMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockUserRepository)(nil).FindAll))
}

// GetByID mocks base method.
func (m *MockUserRepository) GetByID(id uint) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepositoryMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepository)(nil).GetByID), id)
}

// GetByUsername mocks base method.
func (m *MockUserRepository) GetByUsername(username string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUsername", username)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUsername indicates an expected call of GetByUsername.
func (mr *MockUserRepositoryMockRecorder) GetByUsername(username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUsername", reflect.TypeOf((*MockUserRepository)(nil).GetByUsername), username)
}

// MockBorrowRepository is a mock of BorrowRepository interface.
type MockBorrowRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBorrowRepositoryMockRecorder
	isgomock struct{}
}

// MockBorrowRepositoryMockRecorder is the mock recorder for MockBorrowRepository.
type MockBorrowRepositoryMockRecorder struct {
	mock *MockBorrowRepository
}

// NewMockBorrowRepository creates a new mock instance.
func NewMockBorrowRepository(ctrl *gomock.Controller) *MockBorrowRepository {
	mock := &MockBorrowRepository{ctrl: ctrl}
	mock.recorder = &MockBorrowRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBorrowRepository) EXPECT() *MockBorrowRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBorrowRepository) Create(record *models.BorrowRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", record)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBorrowRepositoryMockRecorder) Create(record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBorrowRepository)(nil).Create), record)
}

// FindAll mocks base method.
func (m *MockBorrowRepository) FindAll() ([]*models.BorrowRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].([]*models.BorrowRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockBorrowRepositoryMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockBorrowRepository)(nil).FindAll))
}

// GetByBookID mocks base method.
func (m *MockBorrowRepository) GetByBookID(bookID uint) ([]*models.BorrowRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByBookID", bookID)
	ret0, _ := ret[0].([]*models.BorrowRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByBookID indicates an expected call of GetByBookID.
func (mr *MockBorrowRepositoryMockRecorder) GetByBookID(bookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByBookID", reflect.TypeOf((*MockBorrowRepository)(nil).GetByBookID), bookID)
}

// GetByID mocks base method.
func (m *MockBorrowRepository) GetByID(id uint) (*models.BorrowRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*models.BorrowRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockBorrowRepositoryMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockBorrowRepository)(nil).GetByID), id)
}

// GetByUserAndBook mocks base method.
func (m *MockBorrowRepository) GetByUserAndBook(userID, bookID uint) (*models.BorrowRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserAndBook", userID, bookID)
	ret0, _ := ret[0].(*models.BorrowRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserAndBook indicates an expected call of GetByUserAndBook.
func (mr *MockBorrowRepositoryMockRecorder) GetByUserAndBook(userID, bookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserAndBook", reflect.TypeOf((*MockBorrowRepository)(nil).GetByUserAndBook), userID, bookID)
}

// GetByUserID mocks base method.
func (m *MockBorrowRepository) GetByUserID(userID uint) ([]*models.BorrowRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", userID)
	ret0, _ := ret[0].([]*models.BorrowRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockBorrowRepositoryMockRecorder) GetByUserID(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockBorrowRepository)(nil).GetByUserID), userID)
}

// LockBorrowedRecordForUpdate mocks base method.
func (m *MockBorrowRepository) LockBorrowedRecordForUpdate(userID, bookID uint) (*models.BorrowRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockBorrowedRecordForUpdate", userID, bookID)
	ret0, _ := ret[0].(*models.BorrowRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LockBorrowedRecordForUpdate indicates an expected call of LockBorrowedRecordForUpdate.
func (mr *MockBorrowRepositoryMockRecorder) LockBorrowedRecordForUpdate(userID, bookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockBorrowedRecordForUpdate", reflect.TypeOf((*MockBorrowRepository)(nil).LockBorrowedRecordForUpdate), userID, bookID)
}

// UpdateBorrowRecord mocks base method.
func (m *MockBorrowRepository) UpdateBorrowRecord(record *models.BorrowRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBorrowRecord", record)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBorrowRecord indicates an expected call of UpdateBorrowRecord.
func (mr *MockBorrowRepositoryMockRecorder) UpdateBorrowRecord(record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBorrowRecord", reflect.TypeOf((*MockBorrowRepository)(nil).UpdateBorrowRecord), record)
}
