// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks/mock_interfaces.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/Dailiduzhou/library_manage_sys/models"
	gomock "go.uber.org/mock/gomock"
)

// MockBookService is a mock of BookService interface.
type MockBookService struct {
	ctrl     *gomock.Controller
	recorder *MockBookServiceMockRecorder
	isgomock struct{}
}

// MockBookServiceMockRecorder is the mock recorder for MockBookService.
type MockBookServiceMockRecorder struct {
	mock *MockBookService
}

// NewMockBookService creates a new mock instance.
func NewMockBookService(ctrl *gomock.Controller) *MockBookService {
	mock := &MockBookService{ctrl: ctrl}
	mock.recorder = &MockBookServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookService) EXPECT() *MockBookServiceMockRecorder {
	return m.recorder
}

// CreateBook mocks base method.
func (m *MockBookService) CreateBook(title, author, summary, coverPath string, initialStock int) (*models.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBook", title, author, summary, coverPath, initialStock)
	ret0, _ := ret[0].(*models.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBook indicates an expected call of CreateBook.
func (mr *MockBookServiceMockRecorder) CreateBook(title, author, summary, coverPath, initialStock any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBook", reflect.TypeOf((*MockBookService)(nil).CreateBook), title, author, summary, coverPath, initialStock)
}

// DeleteBook mocks base method.
func (m *MockBookService) DeleteBook(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBook", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBook indicates an expected call of DeleteBook.
func (mr *MockBookServiceMockRecorder) DeleteBook(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBook", reflect.TypeOf((*MockBookService)(nil).DeleteBook), id)
}

// GetBookByID mocks base method.
func (m *MockBookService) GetBookByID(id uint) (*models.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookByID", id)
	ret0, _ := ret[0].(*models.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookByID indicates an expected call of GetBookByID.
func (mr *MockBookServiceMockRecorder) GetBookByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookByID", reflect.TypeOf((*MockBookService)(nil).GetBookByID), id)
}

// GetBooks mocks base method.
func (m *MockBookService) GetBooks(title, author, summary string) ([]models.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBooks", title, author, summary)
	ret0, _ := ret[0].([]models.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBooks indicates an expected call of GetBooks.
func (mr *MockBookServiceMockRecorder) GetBooks(title, author, summary any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBooks", reflect.TypeOf((*MockBookService)(nil).GetBooks), title, author, summary)
}

// UpdateBook mocks base method.
func (m *MockBookService) UpdateBook(id uint, title, author, summary, coverPath string, stock, totalStock int) (*models.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBook", id, title, author, summary, coverPath, stock, totalStock)
	ret0, _ := ret[0].(*models.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBook indicates an expected call of UpdateBook.
func (mr *MockBookServiceMockRecorder) UpdateBook(id, title, author, summary, coverPath, stock, totalStock any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBook", reflect.TypeOf((*MockBookService)(nil).UpdateBook), id, title, author, summary, coverPath, stock, totalStock)
}

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
	isgomock struct{}
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// GetUserByUsername mocks base method.
func (m *MockUserService) GetUserByUsername(username string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUsername", username)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUsername indicates an expected call of GetUserByUsername.
func (mr *MockUserServiceMockRecorder) GetUserByUsername(username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUsername", reflect.TypeOf((*MockUserService)(nil).GetUserByUsername), username)
}

// Login mocks base method.
func (m *MockUserService) Login(username, password string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", username, password)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockUserServiceMockRecorder) Login(username, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockUserService)(nil).Login), username, password)
}

// Register mocks base method.
func (m *MockUserService) Register(username, password string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", username, password)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockUserServiceMockRecorder) Register(username, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockUserService)(nil).Register), username, password)
}

// MockBorrowService is a mock of BorrowService interface.
type MockBorrowService struct {
	ctrl     *gomock.Controller
	recorder *MockBorrowServiceMockRecorder
	isgomock struct{}
}

// MockBorrowServiceMockRecorder is the mock recorder for MockBorrowService.
type MockBorrowServiceMockRecorder struct {
	mock *MockBorrowService
}

// NewMockBorrowService creates a new mock instance.
func NewMockBorrowService(ctrl *gomock.Controller) *MockBorrowService {
	mock := &MockBorrowService{ctrl: ctrl}
	mock.recorder = &MockBorrowServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBorrowService) EXPECT() *MockBorrowServiceMockRecorder {
	return m.recorder
}

// BorrowBook mocks base method.
func (m *MockBorrowService) BorrowBook(userID, bookID uint) (*models.BorrowRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BorrowBook", userID, bookID)
	ret0, _ := ret[0].(*models.BorrowRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BorrowBook indicates an expected call of BorrowBook.
func (mr *MockBorrowServiceMockRecorder) BorrowBook(userID, bookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BorrowBook", reflect.TypeOf((*MockBorrowService)(nil).BorrowBook), userID, bookID)
}

// GetAllRecords mocks base method.
func (m *MockBorrowService) GetAllRecords() ([]models.BorrowRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllRecords")
	ret0, _ := ret[0].([]models.BorrowRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllRecords indicates an expected call of GetAllRecords.
func (mr *MockBorrowServiceMockRecorder) GetAllRecords() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllRecords", reflect.TypeOf((*MockBorrowService)(nil).GetAllRecords))
}

// GetRecordsByUserID mocks base method.
func (m *MockBorrowService) GetRecordsByUserID(userID uint) ([]models.BorrowRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecordsByUserID", userID)
	ret0, _ := ret[0].([]models.BorrowRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecordsByUserID indicates an expected call of GetRecordsByUserID.
func (mr *MockBorrowServiceMockRecorder) GetRecordsByUserID(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecordsByUserID", reflect.TypeOf((*MockBorrowService)(nil).GetRecordsByUserID), userID)
}

// GetUserRecords mocks base method.
func (m *MockBorrowService) GetUserRecords(userID uint) ([]models.BorrowRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRecords", userID)
	ret0, _ := ret[0].([]models.BorrowRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRecords indicates an expected call of GetUserRecords.
func (mr *MockBorrowServiceMockRecorder) GetUserRecords(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRecords", reflect.TypeOf((*MockBorrowService)(nil).GetUserRecords), userID)
}

// ReturnBook mocks base method.
func (m *MockBorrowService) ReturnBook(userID, bookID uint) (*models.BorrowRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReturnBook", userID, bookID)
	ret0, _ := ret[0].(*models.BorrowRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReturnBook indicates an expected call of ReturnBook.
func (mr *MockBorrowServiceMockRecorder) ReturnBook(userID, bookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReturnBook", reflect.TypeOf((*MockBorrowService)(nil).ReturnBook), userID, bookID)
}
